USE master;
GO
IF EXISTS (SELECT * FROM sys.databases WHERE name = 'QLRP')
BEGIN
    ALTER DATABASE QLRP SET SINGLE_USER WITH ROLLBACK IMMEDIATE;
    DROP DATABASE QLRP;
END
GO
CREATE DATABASE QLRP;
GO
USE QLRP;
GO

CREATE TABLE QuocGia (
    MaQuocGia INT PRIMARY KEY IDENTITY(1,1),
    TenQuocGia NVARCHAR(50) NOT NULL
);

CREATE TABLE LoaiGhe (
    MaLoai INT PRIMARY KEY IDENTITY(1,1),
    TenLoaiGhe NVARCHAR(50) NOT NULL,
    PhuThu DECIMAL(18,2) DEFAULT 0
);

CREATE TABLE PhongChieu (
    MaPhong INT PRIMARY KEY IDENTITY(1,1),
    TenPhong NVARCHAR(50) NOT NULL,
    LoaiPhong NVARCHAR(20),
    SucChua INT CHECK (SucChua > 0)
);

CREATE TABLE KhachHang (
    MaKH INT PRIMARY KEY IDENTITY(1,1),
    HoTen NVARCHAR(100) NOT NULL,
    SDT VARCHAR(15) UNIQUE,
    Email VARCHAR(100),
    DiemTichLuy INT DEFAULT 0
);

CREATE TABLE ComboDichVu (
    MaCombo INT PRIMARY KEY IDENTITY(1,1),
    TenCombo NVARCHAR(100) NOT NULL,
    Gia DECIMAL(18,2) CHECK (Gia >= 0)
);

CREATE TABLE Phim (
    MaPhim INT PRIMARY KEY IDENTITY(1,1),
    TenPhim NVARCHAR(200) NOT NULL,
    MaQuocGia INT,
    ThoiLuong INT CHECK (ThoiLuong > 0),
    GioiHanTuoi VARCHAR(10),
    NgayKhoiChieu DATE,
    TrangThai NVARCHAR(50) DEFAULT N'Sắp chiếu',
    CONSTRAINT FK_Phim_QuocGia FOREIGN KEY (MaQuocGia) REFERENCES QuocGia(MaQuocGia)
);

CREATE TABLE Ghe (
    MaGhe INT PRIMARY KEY IDENTITY(1,1),
    MaPhong INT NOT NULL,
    Hang CHAR(1) NOT NULL,
    SoCot INT NOT NULL,
    MaLoai INT,
    CONSTRAINT FK_Ghe_Phong FOREIGN KEY (MaPhong) REFERENCES PhongChieu(MaPhong) ON DELETE CASCADE,
    CONSTRAINT FK_Ghe_Loai FOREIGN KEY (MaLoai) REFERENCES LoaiGhe(MaLoai)
);

CREATE TABLE SuatChieu (
    MaSuat INT PRIMARY KEY IDENTITY(1,1),
    MaPhim INT NOT NULL,
    MaPhong INT NOT NULL,
    NgayChieu DATE NOT NULL,
    GioBatDau TIME NOT NULL,
    GioKetThuc TIME NOT NULL,
    CONSTRAINT FK_SuatChieu_Phim FOREIGN KEY (MaPhim) REFERENCES Phim(MaPhim),
    CONSTRAINT FK_SuatChieu_Phong FOREIGN KEY (MaPhong) REFERENCES PhongChieu(MaPhong)
);

CREATE TABLE HoaDon (
    MaHD INT PRIMARY KEY IDENTITY(1,1),
    MaKH INT,
    NgayLap DATETIME DEFAULT GETDATE(),
    HinhThucThanhToan NVARCHAR(50),
    TrangThai NVARCHAR(50) DEFAULT N'Đã thanh toán',
    CONSTRAINT FK_HoaDon_KhachHang FOREIGN KEY (MaKH) REFERENCES KhachHang(MaKH)
);

CREATE TABLE Ve_ChiTiet (
    MaVe INT PRIMARY KEY IDENTITY(1,1),
    MaHD INT NOT NULL,
    MaSuat INT NOT NULL,
    MaGhe INT NOT NULL,
    GiaVe DECIMAL(18,2) NOT NULL,
    CONSTRAINT FK_Ve_HoaDon FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD),
    CONSTRAINT FK_Ve_SuatChieu FOREIGN KEY (MaSuat) REFERENCES SuatChieu(MaSuat),
    CONSTRAINT FK_Ve_Ghe FOREIGN KEY (MaGhe) REFERENCES Ghe(MaGhe),
    CONSTRAINT UQ_Ghe_Suat UNIQUE (MaSuat, MaGhe)
);

CREATE TABLE HoaDon_Combo (
    MaHD INT NOT NULL,
    MaCombo INT NOT NULL,
    SoLuong INT CHECK (SoLuong > 0),
    PRIMARY KEY (MaHD, MaCombo),
    CONSTRAINT FK_Combo_HoaDon FOREIGN KEY (MaHD) REFERENCES HoaDon(MaHD),
    CONSTRAINT FK_Combo_DV FOREIGN KEY (MaCombo) REFERENCES ComboDichVu(MaCombo)
);
GO